### ISSUE TITLE
A first PyPI 0.2.0 release

### ISSUE THREAD

**Issue by sgillies** [stactools-packages/planet#14]
Hey @gadomski: @cholmes would like to see a release of this package to PyPI. I'm volunteering to be release manager for at least the first few releases. Is there anything I should read about contributing to this plugin project and/or the main stac-utils command project? For example, are plugins versioned separately from the main command? In sync? Is there a roadmap for stac-utils 1.0?

I've gone ahead and created a stactools-planet user on PyPI to be the owner of the stactools-planet package and will invite the stac-utils user to be a maintainer. @gadomski can you add me to the group of contributors for this project so that I can push commits, edit milestones, and set up release infrastructure?

**Comment by gadomski** [comment]
> Is there anything I should read about contributing to this plugin project and/or the main stac-utils command project?

There is existing release infrastructure in https://github.com/stactools-packages/planet/blob/main/.github/workflows/release.yml. Basically, any tag will trigger a release, so be careful (I've screwed it up before on the main **stactools** repo :-) ). You can see a release from a similar **stactools** package here: https://github.com/stactools-packages/noaa-c-cap/actions/runs/1650958664.

This all _should_ be documented but it isn't. I've opened https://github.com/stac-utils/stactools/issues/221 to capture that need.

> are plugins versioned separately from the main command?

Yup, separate versioning.

> Is there a roadmap for stac-utils 1.0?

I'm assuming you mean **stactools** instead of **stac-utils**? If so, no, there is no roadmap at this time, but I'd be supportive of that effort.

> can you add me to the group of contributors for this project so that I can push commits, edit milestones, and set up release infrastructure?

Done.

**Comment by sgillies** [comment]
@gadomski thanks! No need for the new PyPI user then :pray:

**Comment by sgillies** [comment]
I'm proposing version 0.2.0 for the release, a minor bump from 0.1.6 (last time the planet command was included in the main package).

**Comment by sgillies** [comment]
Et voilà https://pypi.org/project/stactools-planet/0.2.0/.

Nice work on the release workflow @gadomski !

**Comment by gadomski** [comment]
🙇🏽 thanks, though I didn't make most of it, @lossyrob and @cuttlefish and others did most :-)! Congrats on the release 🥳!
